nome = str(input('Digite seu nome completo: ')).strip()
print('Analisando seu nome...')
print('Seu nome em maiúsculas é: {}'.format(nome.upper()))
print('Seu nome em minúsculas é: {}'.format(nome.lower()))
div = nome.split()
print('Seu primeiro nome é {} e possui {} letras.'.format(div[0], len(div[0])))
print('Seu nome possui {} letras ao todo !.'.format(len(nome) - nome.count(' ')))
